/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesResidentialRouteImport } from './routes/services.residential'
import { Route as ServicesPackingRouteImport } from './routes/services.packing'
import { Route as ServicesOfficeRouteImport } from './routes/services.office'
import { Route as ServicesMountingRouteImport } from './routes/services.mounting'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalInsuranceRouteImport } from './routes/legal.insurance'
import { Route as GlobalProjectCargoRouteImport } from './routes/global.project-cargo'
import { Route as GlobalOceanRouteImport } from './routes/global.ocean'
import { Route as GlobalColdChainRouteImport } from './routes/global.cold-chain'
import { Route as GlobalAirRouteImport } from './routes/global.air'
import { Route as FreightTruckHireRouteImport } from './routes/freight.truck-hire'
import { Route as FreightPetroleumRouteImport } from './routes/freight.petroleum'
import { Route as FreightLtlRouteImport } from './routes/freight.ltl'
import { Route as FreightIndustrialRouteImport } from './routes/freight.industrial'
import { Route as FreightFtlRouteImport } from './routes/freight.ftl'

const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesResidentialRoute = ServicesResidentialRouteImport.update({
  id: '/services/residential',
  path: '/services/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPackingRoute = ServicesPackingRouteImport.update({
  id: '/services/packing',
  path: '/services/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOfficeRoute = ServicesOfficeRouteImport.update({
  id: '/services/office',
  path: '/services/office',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMountingRoute = ServicesMountingRouteImport.update({
  id: '/services/mounting',
  path: '/services/mounting',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalInsuranceRoute = LegalInsuranceRouteImport.update({
  id: '/legal/insurance',
  path: '/legal/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalProjectCargoRoute = GlobalProjectCargoRouteImport.update({
  id: '/global/project-cargo',
  path: '/global/project-cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalOceanRoute = GlobalOceanRouteImport.update({
  id: '/global/ocean',
  path: '/global/ocean',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalColdChainRoute = GlobalColdChainRouteImport.update({
  id: '/global/cold-chain',
  path: '/global/cold-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalAirRoute = GlobalAirRouteImport.update({
  id: '/global/air',
  path: '/global/air',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightTruckHireRoute = FreightTruckHireRouteImport.update({
  id: '/freight/truck-hire',
  path: '/freight/truck-hire',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightPetroleumRoute = FreightPetroleumRouteImport.update({
  id: '/freight/petroleum',
  path: '/freight/petroleum',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightLtlRoute = FreightLtlRouteImport.update({
  id: '/freight/ltl',
  path: '/freight/ltl',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightIndustrialRoute = FreightIndustrialRouteImport.update({
  id: '/freight/industrial',
  path: '/freight/industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightFtlRoute = FreightFtlRouteImport.update({
  id: '/freight/ftl',
  path: '/freight/ftl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/coverage': typeof CoverageRoute
  '/fleet': typeof FleetRoute
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/freight/ftl': typeof FreightFtlRoute
  '/freight/industrial': typeof FreightIndustrialRoute
  '/freight/ltl': typeof FreightLtlRoute
  '/freight/petroleum': typeof FreightPetroleumRoute
  '/freight/truck-hire': typeof FreightTruckHireRoute
  '/global/air': typeof GlobalAirRoute
  '/global/cold-chain': typeof GlobalColdChainRoute
  '/global/ocean': typeof GlobalOceanRoute
  '/global/project-cargo': typeof GlobalProjectCargoRoute
  '/legal/insurance': typeof LegalInsuranceRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/mounting': typeof ServicesMountingRoute
  '/services/office': typeof ServicesOfficeRoute
  '/services/packing': typeof ServicesPackingRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/coverage': typeof CoverageRoute
  '/fleet': typeof FleetRoute
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/freight/ftl': typeof FreightFtlRoute
  '/freight/industrial': typeof FreightIndustrialRoute
  '/freight/ltl': typeof FreightLtlRoute
  '/freight/petroleum': typeof FreightPetroleumRoute
  '/freight/truck-hire': typeof FreightTruckHireRoute
  '/global/air': typeof GlobalAirRoute
  '/global/cold-chain': typeof GlobalColdChainRoute
  '/global/ocean': typeof GlobalOceanRoute
  '/global/project-cargo': typeof GlobalProjectCargoRoute
  '/legal/insurance': typeof LegalInsuranceRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/mounting': typeof ServicesMountingRoute
  '/services/office': typeof ServicesOfficeRoute
  '/services/packing': typeof ServicesPackingRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/coverage': typeof CoverageRoute
  '/fleet': typeof FleetRoute
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/freight/ftl': typeof FreightFtlRoute
  '/freight/industrial': typeof FreightIndustrialRoute
  '/freight/ltl': typeof FreightLtlRoute
  '/freight/petroleum': typeof FreightPetroleumRoute
  '/freight/truck-hire': typeof FreightTruckHireRoute
  '/global/air': typeof GlobalAirRoute
  '/global/cold-chain': typeof GlobalColdChainRoute
  '/global/ocean': typeof GlobalOceanRoute
  '/global/project-cargo': typeof GlobalProjectCargoRoute
  '/legal/insurance': typeof LegalInsuranceRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/mounting': typeof ServicesMountingRoute
  '/services/office': typeof ServicesOfficeRoute
  '/services/packing': typeof ServicesPackingRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/coverage'
    | '/fleet'
    | '/gallery'
    | '/quote'
    | '/freight/ftl'
    | '/freight/industrial'
    | '/freight/ltl'
    | '/freight/petroleum'
    | '/freight/truck-hire'
    | '/global/air'
    | '/global/cold-chain'
    | '/global/ocean'
    | '/global/project-cargo'
    | '/legal/insurance'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/mounting'
    | '/services/office'
    | '/services/packing'
    | '/services/residential'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/coverage'
    | '/fleet'
    | '/gallery'
    | '/quote'
    | '/freight/ftl'
    | '/freight/industrial'
    | '/freight/ltl'
    | '/freight/petroleum'
    | '/freight/truck-hire'
    | '/global/air'
    | '/global/cold-chain'
    | '/global/ocean'
    | '/global/project-cargo'
    | '/legal/insurance'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/mounting'
    | '/services/office'
    | '/services/packing'
    | '/services/residential'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/coverage'
    | '/fleet'
    | '/gallery'
    | '/quote'
    | '/freight/ftl'
    | '/freight/industrial'
    | '/freight/ltl'
    | '/freight/petroleum'
    | '/freight/truck-hire'
    | '/global/air'
    | '/global/cold-chain'
    | '/global/ocean'
    | '/global/project-cargo'
    | '/legal/insurance'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/mounting'
    | '/services/office'
    | '/services/packing'
    | '/services/residential'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CoverageRoute: typeof CoverageRoute
  FleetRoute: typeof FleetRoute
  GalleryRoute: typeof GalleryRoute
  QuoteRoute: typeof QuoteRoute
  FreightFtlRoute: typeof FreightFtlRoute
  FreightIndustrialRoute: typeof FreightIndustrialRoute
  FreightLtlRoute: typeof FreightLtlRoute
  FreightPetroleumRoute: typeof FreightPetroleumRoute
  FreightTruckHireRoute: typeof FreightTruckHireRoute
  GlobalAirRoute: typeof GlobalAirRoute
  GlobalColdChainRoute: typeof GlobalColdChainRoute
  GlobalOceanRoute: typeof GlobalOceanRoute
  GlobalProjectCargoRoute: typeof GlobalProjectCargoRoute
  LegalInsuranceRoute: typeof LegalInsuranceRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ServicesMountingRoute: typeof ServicesMountingRoute
  ServicesOfficeRoute: typeof ServicesOfficeRoute
  ServicesPackingRoute: typeof ServicesPackingRoute
  ServicesResidentialRoute: typeof ServicesResidentialRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/residential': {
      id: '/services/residential'
      path: '/services/residential'
      fullPath: '/services/residential'
      preLoaderRoute: typeof ServicesResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/packing': {
      id: '/services/packing'
      path: '/services/packing'
      fullPath: '/services/packing'
      preLoaderRoute: typeof ServicesPackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/office': {
      id: '/services/office'
      path: '/services/office'
      fullPath: '/services/office'
      preLoaderRoute: typeof ServicesOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mounting': {
      id: '/services/mounting'
      path: '/services/mounting'
      fullPath: '/services/mounting'
      preLoaderRoute: typeof ServicesMountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/insurance': {
      id: '/legal/insurance'
      path: '/legal/insurance'
      fullPath: '/legal/insurance'
      preLoaderRoute: typeof LegalInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/project-cargo': {
      id: '/global/project-cargo'
      path: '/global/project-cargo'
      fullPath: '/global/project-cargo'
      preLoaderRoute: typeof GlobalProjectCargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/ocean': {
      id: '/global/ocean'
      path: '/global/ocean'
      fullPath: '/global/ocean'
      preLoaderRoute: typeof GlobalOceanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/cold-chain': {
      id: '/global/cold-chain'
      path: '/global/cold-chain'
      fullPath: '/global/cold-chain'
      preLoaderRoute: typeof GlobalColdChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/air': {
      id: '/global/air'
      path: '/global/air'
      fullPath: '/global/air'
      preLoaderRoute: typeof GlobalAirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight/truck-hire': {
      id: '/freight/truck-hire'
      path: '/freight/truck-hire'
      fullPath: '/freight/truck-hire'
      preLoaderRoute: typeof FreightTruckHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight/petroleum': {
      id: '/freight/petroleum'
      path: '/freight/petroleum'
      fullPath: '/freight/petroleum'
      preLoaderRoute: typeof FreightPetroleumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight/ltl': {
      id: '/freight/ltl'
      path: '/freight/ltl'
      fullPath: '/freight/ltl'
      preLoaderRoute: typeof FreightLtlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight/industrial': {
      id: '/freight/industrial'
      path: '/freight/industrial'
      fullPath: '/freight/industrial'
      preLoaderRoute: typeof FreightIndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight/ftl': {
      id: '/freight/ftl'
      path: '/freight/ftl'
      fullPath: '/freight/ftl'
      preLoaderRoute: typeof FreightFtlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CoverageRoute: CoverageRoute,
  FleetRoute: FleetRoute,
  GalleryRoute: GalleryRoute,
  QuoteRoute: QuoteRoute,
  FreightFtlRoute: FreightFtlRoute,
  FreightIndustrialRoute: FreightIndustrialRoute,
  FreightLtlRoute: FreightLtlRoute,
  FreightPetroleumRoute: FreightPetroleumRoute,
  FreightTruckHireRoute: FreightTruckHireRoute,
  GlobalAirRoute: GlobalAirRoute,
  GlobalColdChainRoute: GlobalColdChainRoute,
  GlobalOceanRoute: GlobalOceanRoute,
  GlobalProjectCargoRoute: GlobalProjectCargoRoute,
  LegalInsuranceRoute: LegalInsuranceRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ServicesMountingRoute: ServicesMountingRoute,
  ServicesOfficeRoute: ServicesOfficeRoute,
  ServicesPackingRoute: ServicesPackingRoute,
  ServicesResidentialRoute: ServicesResidentialRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
